from PyQt5 import QtWidgets

class Ui_Stats(object):

    def setupUi(self, Dialog, gestore):
        self.gestore = gestore
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        Dialog.setWindowTitle("Statistiche")
        self.labelSag = QtWidgets.QLabel(Dialog)
        self.labelSag.setText("Saggezza media")
        self.gridLayout.addWidget(self.labelSag, 5, 0, 1, 1)
        self.labelInt = QtWidgets.QLabel(Dialog)
        self.labelInt.setText("Intelligenza media")
        self.gridLayout.addWidget(self.labelInt, 4, 0, 1, 1)
        self.textSagg = QtWidgets.QLabel(Dialog)
        self.gridLayout.addWidget(self.textSagg, 5, 1, 1, 1)
        self.textInt = QtWidgets.QLabel(Dialog)
        self.gridLayout.addWidget(self.textInt, 4, 1, 1, 1)
        self.labelCon = QtWidgets.QLabel(Dialog)
        self.labelCon.setText("Costituzione media")
        self.gridLayout.addWidget(self.labelCon, 3, 0, 1, 1)
        self.textDestr = QtWidgets.QLabel(Dialog)
        self.gridLayout.addWidget(self.textDestr, 2, 1, 1, 1)
        self.labelCar = QtWidgets.QLabel(Dialog)
        self.labelCar.setText("Carisma medio")
        self.gridLayout.addWidget(self.labelCar, 6, 0, 1, 1)
        self.labelForza = QtWidgets.QLabel(Dialog)
        self.labelForza.setText("Forza media")
        self.gridLayout.addWidget(self.labelForza, 1, 0, 1, 1)
        self.labelDestrezza = QtWidgets.QLabel(Dialog)
        self.labelDestrezza.setText("Destrezza media")
        self.gridLayout.addWidget(self.labelDestrezza, 2, 0, 1, 1)
        self.textCar = QtWidgets.QLabel(Dialog)
        self.gridLayout.addWidget(self.textCar, 6, 1, 1, 1)
        self.textCost = QtWidgets.QLabel(Dialog)
        self.gridLayout.addWidget(self.textCost, 3, 1, 1, 1)
        self.textForza = QtWidgets.QLabel(Dialog)
        self.gridLayout.addWidget(self.textForza, 1, 1, 1, 1)
        self.labelCA = QtWidgets.QLabel(Dialog)
        self.labelCA.setText("Classe Armatura media")
        self.gridLayout.addWidget(self.labelCA, 10, 0, 1, 1)
        self.textLivello = QtWidgets.QLabel(Dialog)
        self.gridLayout.addWidget(self.textLivello, 8, 1, 1, 1)
        self.labelPF = QtWidgets.QLabel(Dialog)
        self.labelPF.setText("Punti Ferita medi")
        self.gridLayout.addWidget(self.labelPF, 9, 0, 1, 1)
        self.textPF = QtWidgets.QLabel(Dialog)
        self.gridLayout.addWidget(self.textPF, 9, 1, 1, 1)
        self.labelLivello = QtWidgets.QLabel(Dialog)
        self.labelLivello.setText("Livello medio")
        self.gridLayout.addWidget(self.labelLivello, 8, 0, 1, 1)
        self.textCA = QtWidgets.QLabel(Dialog)
        self.gridLayout.addWidget(self.textCA, 10, 1, 1, 1)

        self.visualizzastats()

    def visualizzastats(self):
        stats = self.gestore.creaStatistiche()
        self.textPF.setText(str(stats[0]))
        self.textCA.setText(str(stats[1]))
        self.textLivello.setText(str(stats[2]))
        self.textForza.setText(str(stats[3]))
        self.textDestr.setText(str(stats[4]))
        self.textCost.setText(str(stats[5]))
        self.textInt.setText(str(stats[6]))
        self.textSagg.setText(str(stats[7]))
        self.textCar.setText(str(stats[8]))
        return
