# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Note.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form, gestoreGiocatore):
        self.gestoreGiocatore = gestoreGiocatore
        Form.setObjectName("Form")
        Form.resize(520, 337)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(1, 1))
        self.label.setMaximumSize(QtCore.QSize(16777215, 41))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.textEdit.setText(self.gestoreGiocatore.visualizzaNote())
        self.buttonConferma = QtWidgets.QPushButton(Form)
        self.verticalLayout.addWidget(self.buttonConferma)
        self.buttonConferma.clicked.connect(self.salvaNote)
        self.buttonConferma.setText("Salva note")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Note"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Note:</span></p></body></html>"))


    def salvaNote(self):
        self.gestoreGiocatore.modificaNote(self.textEdit.toPlainText())

