# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\visualizzaAppunto.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, gestore):
        self.gestore = gestore
        self.MainWindow = MainWindow
        self.layout = QtWidgets.QVBoxLayout(MainWindow)
        self.immagineAppunto = QtWidgets.QLabel(MainWindow)
        self.testoAppunto = QtWidgets.QTextBrowser(MainWindow)
        self.layout.addWidget(self.immagineAppunto)
        self.layout.addWidget(self.testoAppunto)

        self.visualizza()

    def visualizza(self):
        self.gestore.visualizzaAppunti(self.gestore.appunto.getNome())
        self.testoAppunto.setText(self.gestore.appunto.getInformazioni())
        print(self.gestore.appunto.getImmagine())
        if self.gestore.appunto.getImmagine() == None:
            self.immagineAppunto.setText("Nessuna immagine per questo appunto")
        else:
            pixmap = QPixmap("Appunti/" + self.gestore.appunto.getNome() + ".jpg")
            self.immagineAppunto.setPixmap(pixmap)
