# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dado.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Controller import Giocatore, Master


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, gestore):
        self.gestore = gestore
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(332, 363)
        MainWindow.setMinimumSize(QtCore.QSize(332, 363))
        MainWindow.setMaximumSize(QtCore.QSize(332, 363))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dadoTesto = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dadoTesto.setFont(font)
        self.dadoTesto.setObjectName("dadoTesto")
        self.verticalLayout.addWidget(self.dadoTesto)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.layoutScelta = QtWidgets.QHBoxLayout()
        self.layoutScelta.setObjectName("layoutScelta")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tipoDado = QtWidgets.QComboBox(self.centralwidget)
        self.tipoDado.setObjectName("tipoDado")
        self.tipoDado.addItem("")
        self.tipoDado.addItem("")
        self.tipoDado.addItem("")
        self.tipoDado.addItem("")
        self.tipoDado.addItem("")
        self.tipoDado.addItem("")
        self.tipoDado.addItem("")
        self.gridLayout.addWidget(self.tipoDado, 0, 1, 1, 1)
        self.numDadi = QtWidgets.QComboBox(self.centralwidget)
        self.numDadi.setObjectName("numDadi")
        self.numDadi.addItem("")
        self.numDadi.addItem("")
        self.numDadi.addItem("")
        self.numDadi.addItem("")
        self.numDadi.addItem("")
        self.numDadi.addItem("")
        self.numDadi.addItem("")
        self.numDadi.addItem("")
        self.numDadi.addItem("")
        self.numDadi.addItem("")
        self.gridLayout.addWidget(self.numDadi, 0, 0, 1, 1)
        self.buttonTira = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTira.setObjectName("buttonTira")
        self.gridLayout.addWidget(self.buttonTira, 1, 0, 1, 2)
        self.buttonTira.clicked.connect(self.tiraDadi)
        self.layoutScelta.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.layoutScelta)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelRisultato = QtWidgets.QLabel(self.centralwidget)
        self.labelRisultato.setMinimumSize(QtCore.QSize(158, 78))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelRisultato.setFont(font)
        self.labelRisultato.setObjectName("labelRisultato")
        self.horizontalLayout.addWidget(self.labelRisultato)
        self.lineRisultato = QtWidgets.QLineEdit(self.centralwidget)
        self.lineRisultato.setObjectName("lineRisultato")
        self.horizontalLayout.addWidget(self.lineRisultato)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DnD Manager"))
        self.dadoTesto.setText(_translate("MainWindow", "Scegli il numero e il tipo di dadi da lanciare:"))
        self.tipoDado.setItemText(0, _translate("MainWindow", "4"))
        self.tipoDado.setItemText(1, _translate("MainWindow", "6"))
        self.tipoDado.setItemText(2, _translate("MainWindow", "8"))
        self.tipoDado.setItemText(3, _translate("MainWindow", "10"))
        self.tipoDado.setItemText(4, _translate("MainWindow", "12"))
        self.tipoDado.setItemText(5, _translate("MainWindow", "20"))
        self.tipoDado.setItemText(6, _translate("MainWindow", "100"))
        self.numDadi.setItemText(0, _translate("MainWindow", "1"))
        self.numDadi.setItemText(1, _translate("MainWindow", "2"))
        self.numDadi.setItemText(2, _translate("MainWindow", "3"))
        self.numDadi.setItemText(3, _translate("MainWindow", "4"))
        self.numDadi.setItemText(4, _translate("MainWindow", "5"))
        self.numDadi.setItemText(5, _translate("MainWindow", "6"))
        self.numDadi.setItemText(6, _translate("MainWindow", "7"))
        self.numDadi.setItemText(7, _translate("MainWindow", "8"))
        self.numDadi.setItemText(8, _translate("MainWindow", "9"))
        self.numDadi.setItemText(9, _translate("MainWindow", "10"))
        self.buttonTira.setText(_translate("MainWindow", "Tira"))
        self.labelRisultato.setText(_translate("MainWindow", "Risultato:"))

    def tiraDadi(self):
        self.lineRisultato.setText(self.gestore.tiraDado(self.tipoDado.currentText(), self.numDadi.currentText()))

