# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MenuGiocatore.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Controller import Giocatore
from View import VistaCreaScheda, VistaAccesso, VistaVisualizzaScheda
from Model import Utente

class Ui_Form(object):
    def setupUi(self, Form, currentUtente):
        self.gestoreGiocatore = Giocatore.Giocatore(currentUtente)
        Form.setObjectName("DnD Manager")
        Form.resize(566, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buttonCambiaCredenziali = QtWidgets.QPushButton(Form)
        self.buttonCambiaCredenziali.setEnabled(True)
        self.buttonCambiaCredenziali.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.buttonCambiaCredenziali, 0, 1, 1, 1)
        self.buttonCreaScheda = QtWidgets.QPushButton(Form)
        self.buttonCreaScheda.setObjectName("buttonCreaScheda")
        self.gridLayout.addWidget(self.buttonCreaScheda, 1, 0, 1, 1)
        self.buttonCreaScheda.clicked.connect(self.goCreaScheda)
        self.buttonVisualizzaScheda = QtWidgets.QPushButton(Form)
        self.buttonVisualizzaScheda.setObjectName("pushButton")
        self.gridLayout.addWidget(self.buttonVisualizzaScheda, 1, 1, 1, 1)
        self.buttonVisualizzaScheda.clicked.connect(self.goVisualizzaScheda)
        self.buttonModificaScheda = QtWidgets.QPushButton(Form)
        self.buttonModificaScheda.setEnabled(True)
        self.buttonModificaScheda.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.buttonModificaScheda, 1, 2, 1, 1)
        self.buttonVisualizzaDispense = QtWidgets.QPushButton(Form)
        self.buttonVisualizzaDispense.setEnabled(True)
        self.buttonVisualizzaDispense.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.buttonVisualizzaDispense, 2, 0, 1, 1)
        self.buttonTiraDadi = QtWidgets.QPushButton(Form)
        self.buttonTiraDadi.setEnabled(True)
        self.buttonTiraDadi.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.buttonTiraDadi, 2, 1, 1, 1)
        self.buttonNote = QtWidgets.QPushButton(Form)
        self.buttonNote.setEnabled(True)
        self.buttonNote.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.buttonNote, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DnD Manager"))
        self.label.setText(_translate("Form", ("<html><head/><body><p><span style=\" font-size:14pt;\">Id:" + self.gestoreGiocatore.utente.id + "</span></p><p><span style=\" font-size:14pt;\">Ruolo: Giocatore</span></p><p><span style=\" font-size:14pt;\">Utente: " + self.gestoreGiocatore.utente.getNomeUtente() + "</span></p><p><br/></p></body></html>")))
        self.buttonCambiaCredenziali.setText(_translate("Form", "Cambia Credenziali"))
        self.buttonCreaScheda.setText(_translate("Form", "Crea Scheda"))
        self.buttonVisualizzaScheda.setText(_translate("Form", "Visualizza Scheda"))
        self.buttonModificaScheda.setText(_translate("Form", "Modifica Scheda"))
        self.buttonVisualizzaDispense.setText(_translate("Form", "Visualizza Dispense"))
        self.buttonTiraDadi.setText(_translate("Form", "Tira i dadi"))
        self.buttonNote.setText(_translate("Form", "Note"))


    def goCreaScheda(self):
        if self.gestoreGiocatore.utente.personaggio.getNome() != "":
            popup = QtWidgets.QMessageBox()
            popup.setText("Personaggio già esisente")
            popup.setWindowTitle("Errore")
            popup.exec_()
            return
        self.ui = VistaCreaScheda.Ui_MainWindow()
        windowCreaScheda = QtWidgets.QMainWindow()
        VistaAccesso.Ui_Login.windowList.append(windowCreaScheda)
        self.ui.setupUi(windowCreaScheda, self.gestoreGiocatore)
        windowCreaScheda.show()

    def goVisualizzaScheda(self):
        if self.gestoreGiocatore.utente.personaggio.getNome() == "":
            popup = QtWidgets.QMessageBox()
            popup.setText("Devi prima creare il personaggio")
            popup.setWindowTitle("Errore")
            popup.exec_()
            return
        self.ui = VistaVisualizzaScheda.Ui_Scheda()
        windowVisScheda = QtWidgets.QDialog()
        VistaAccesso.Ui_Login.windowList.append(windowVisScheda)
        self.ui.setupUi(windowVisScheda, self.gestoreGiocatore)
        windowVisScheda.show()



