# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MenuMaster.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Controller import Master
from View import VistaCambioCredenziali, VistaAccesso, VistaDado, VistaTrovaPersonaggio


class Ui_Form(object):
    def setupUi(self, Form, master):
        self.gestoreMaster = Master.Master(master)
        Form.setObjectName("Form")
        Form.resize(637, 454)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buttonCredenziali = QtWidgets.QPushButton(Form)
        self.buttonCredenziali.setEnabled(True)
        self.buttonCredenziali.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.buttonCredenziali, 0, 0, 1, 1)
        self.buttonCredenziali.clicked.connect(self.goCredenziali)
        self.buttonModPG = QtWidgets.QPushButton(Form)
        self.buttonModPG.setEnabled(True)
        self.buttonModPG.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.buttonModPG, 0, 1, 1, 1)
        self.buttonVisPG = QtWidgets.QPushButton(Form)
        self.buttonVisPG.setEnabled(True)
        self.buttonVisPG.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.buttonVisPG, 0, 2, 1, 1)
        self.buttonVisPG.clicked.connect(self.goTrovaPG)
        self.buttonCreaAppunto = QtWidgets.QPushButton(Form)
        self.buttonCreaAppunto.setEnabled(True)
        self.buttonCreaAppunto.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.buttonCreaAppunto, 1, 0, 1, 1)
        self.buttonVisAppunto = QtWidgets.QPushButton(Form)
        self.buttonVisAppunto.setEnabled(True)
        self.buttonVisAppunto.setObjectName("pushButton")
        self.gridLayout.addWidget(self.buttonVisAppunto, 1, 1, 1, 1)
        self.buttonModifAppunto = QtWidgets.QPushButton(Form)
        self.buttonModifAppunto.setEnabled(True)
        self.buttonModifAppunto.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.buttonModifAppunto, 1, 2, 1, 1)
        self.buttonElimAppunto = QtWidgets.QPushButton(Form)
        self.buttonElimAppunto.setEnabled(True)
        self.buttonElimAppunto.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.buttonElimAppunto, 2, 0, 1, 1)
        self.buttonDadi = QtWidgets.QPushButton(Form)
        self.buttonDadi.setEnabled(True)
        self.buttonDadi.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.buttonDadi, 2, 1, 1, 1)
        self.buttonDadi.clicked.connect(self.goDadi)
        self.buttonStats = QtWidgets.QPushButton(Form)
        self.buttonStats.setEnabled(True)
        self.buttonStats.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.buttonStats, 2, 2, 1, 1)
        self.buttonContatore = QtWidgets.QPushButton(Form)
        self.buttonContatore.setEnabled(True)
        self.buttonContatore.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.buttonContatore, 3, 0, 1, 1)
        self.buttonPubblica = QtWidgets.QPushButton(Form)
        self.buttonPubblica.setEnabled(True)
        self.buttonPubblica.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.buttonPubblica, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DnD Manager"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Id: 7123</span></p><p><span style=\" font-size:14pt;\">Ruolo: Master</span></p><p><br/></p></body></html>"))
        self.buttonCredenziali.setText(_translate("Form", "Cambia Credenziali"))
        self.buttonModPG.setText(_translate("Form", "Modifica PG"))
        self.buttonVisPG.setText(_translate("Form", "Visualizza PG"))
        self.buttonCreaAppunto.setText(_translate("Form", "Crea Appunto"))
        self.buttonVisAppunto.setText(_translate("Form", "Visualizza Appunto"))
        self.buttonModifAppunto.setText(_translate("Form", "Modifica Appunto"))
        self.buttonElimAppunto.setText(_translate("Form", "Elimina Appunto"))
        self.buttonDadi.setText(_translate("Form", "Tira i dadi"))
        self.buttonStats.setText(_translate("Form", "Genera Statistiche"))
        self.buttonContatore.setText(_translate("Form", "Gestisci Contatore"))
        self.buttonPubblica.setText(_translate("Form", "Pubblica Appunti"))


    def goCredenziali(self):
        self.ui = VistaCambioCredenziali.Ui_Form()
        windowCredenziali = QtWidgets.QDialog()
        VistaAccesso.Ui_Login.windowList.append(windowCredenziali)
        self.ui.setupUi(windowCredenziali, self.gestoreMaster.utente)
        windowCredenziali.show()

    def goDadi(self):
        self.ui = VistaDado.Ui_MainWindow()
        windowDado = QtWidgets.QMainWindow()
        VistaAccesso.Ui_Login.windowList.append(windowDado)
        self.ui.setupUi(windowDado, self.gestoreMaster)
        windowDado.show()

    def goTrovaPG(self):
        self.ui = VistaTrovaPersonaggio.Ui_TrovaPG()
        windowTrovaPG = QtWidgets.QDialog()
        VistaAccesso.Ui_Login.windowList.append(windowTrovaPG)
        self.ui.setupUi(windowTrovaPG)
        windowTrovaPG.show()
