# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GestisciContatore.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Controller import Master


class Ui_Form(object):
    def setupUi(self, Form, gestore):
        self.gestore = gestore
        Form.setObjectName("Form")
        Form.resize(602, 370)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setMinimumSize(QtCore.QSize(1, 1))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonIncr = QtWidgets.QPushButton(Form)
        self.buttonIncr.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.buttonIncr)
        self.buttonIncr.clicked.connect(self.incrementaCont)
        self.buttonReset = QtWidgets.QPushButton(Form)
        self.buttonReset.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.buttonReset)
        self.buttonReset.clicked.connect(self.resettaCont)
        self.verticalLayout.addLayout(self.horizontalLayout)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.inizializza()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Contatore"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Numero sessioni:</span></p></body></html>"))
        self.textBrowser.setText("<html><head/><body><p><span style=\" font-size:12pt;\">0</span></p></body></html>")
        self.buttonIncr.setText(_translate("Form", "Incrementa"))
        self.buttonReset.setText(_translate("Form", "Resetta"))

    def inizializza(self):
        self.gestore.caricaContatore()
        self.textBrowser.setText("<html><head/><body><p><span style=\" font-size:12pt;\">" + self.gestore.visualizzaContatore() + "</span></p></body></html>")
        self.gestore.salvaContatore()

    def incrementaCont(self):
        self.gestore.incrementaContatore()
        self.textBrowser.setText("<html><head/><body><p><span style=\" font-size:12pt;\">" + self.gestore.visualizzaContatore() + "</span></p></body></html>")
        self.gestore.salvaContatore()

    def resettaCont(self):
        self.gestore.resettaContatore()
        self.textBrowser.setText("<html><head/><body><p><span style=\" font-size:12pt;\">" + self.gestore.visualizzaContatore() + "</span></p></body></html>")
        self.gestore.salvaContatore()
